# inventory/defaults.yaml
---
username: "${NORNIR_USERNAME}"
password: "${NORNIR_PASSWORD}"

ntp:
  servers:
    - 10.1.1.254
  source: Ethernet1/3

syslog:
  servers:
    - 10.1.1.254
  source: Ethernet1/3
  facility: local6

ospf_auth:
  key_id: 1
  key: "${OSPF_AUTH_KEY}"

ospf_reference_bandwidth: 100
