# host_vars/ce1.yaml
hostname: CE1
loopback_name: Loopback0
role: ce
iou: 7

domain_name: lab.local

mgmt:
  vrf: Mgmt-intf
  interface: Ethernet1/3
  ip: 10.1.1.7
  mask: 255.255.255.0
  gateway: 10.1.1.254

interfaces:
  - name: Loopback0
    description: "Router ID"
    ip: 77.77.77.77
    mask: 255.255.255.255
  - name: Ethernet1/0
    description: "link to PE1"
    ip: 172.1.17.7
    mask: 255.255.255.0

bgp:
  asn: 65001
  router_id: 77.77.77.77

  neighbors:
    - ip: 172.1.17.1
      remote_as: 65
      description: "PE1"
      route_map_in: PE1-IN
      route_map_out: PE1-OUT
      # allowas_in: 1         # integer, renders as "allowas-in 1"