# host_vars/ce1.yaml
hostname: CE1
loopback_name: Loopback0
iou: 7

domain_name: lab.local

mgmt:
  vrf: Mgmt-intf
  interface: Ethernet1/3
  ip: 10.1.1.7
  mask: 255.255.255.0
  gateway: 10.1.1.254

interfaces:
  - name: Loopback0
    description: "Router ID"
    ip: 77.77.77.77
    mask: 255.255.255.255
  - name: Ethernet1/0
    description: "link to PE1"
    ip: 172.1.17.7
    mask: 255.255.255.0

bgp:
  asn: 65001
  router_id: 77.77.77.77
  networks:
    - prefix: 77.77.77.77
      mask: 255.255.255.255

  neighbors:
    - ip: 172.1.17.1
      remote_as: 65
      description: "PE1"
      route_map_in: PE1-IN
      route_map_out: PE1-OUT
      # allowas_in: 1         # integer, renders as "allowas-in 1"

prefix_lists:
  - name: PE1-PREFIXES
    entries:
      - seq: 10
        action: permit
        prefix: 0.0.0.0/0
        le: 32

route_maps:
  - name: PE1-IN
    description: "Accept routes from PE1"
    entries:
      - seq: 10
        action: permit
        match: "ip address prefix-list PE1-PREFIXES"

  - name: PE1-OUT
    description: "Advertise CE1 prefixes to PE1"
    entries:
      - seq: 999
        action: permit
