# host_vars/ce2.yaml
hostname: CE2
loopback_name: Loopback0
role: ce
iou: 8

domain_name: lab.local

mgmt:
  vrf: Mgmt-intf
  interface: Ethernet1/3
  ip: 10.1.1.8
  mask: 255.255.255.0
  gateway: 10.1.1.254

interfaces:
  - name: Loopback0
    description: "Router ID"
    ip: 88.88.88.88
    mask: 255.255.255.255
  - name: Ethernet1/0
    description: "link to PE2"
    ip: 172.1.28.8
    mask: 255.255.255.0