# host_vars/pe1.yaml
hostname: PE1
loopback_name: Loopback0
role: pe
iou: 1

domain_name: lab.local

mgmt:
  vrf: Mgmt-intf
  interface: Ethernet1/3
  ip: 10.1.1.1
  mask: 255.255.255.0
  gateway: 10.1.1.254

ospf:
  process_id: 1
  router_id: 1.1.1.1
  reference_bandwidth: 1000000
  passive_interfaces:
    - Loopback0
    - Ethernet1/0

vrfs:
  - name: VRF_A
    rd: "65:65001"
    rt_export: "65:65001"
    rt_import: "65:65001"

interfaces:
  - name: Loopback0
    description: "Router ID"
    ip: 1.1.1.1
    mask: 255.255.255.255
    ospf:
      process: 1
      area: 0
  - name: Ethernet0/0
    description: "link to P1"
    ip: 10.1.2.1
    mask: 255.255.255.0
    mpls: true
    ospf:
      process: 1
      area: 0
      network_type: point-to-point
  - name: Ethernet1/0
    description: "VRF A to CE1"
    ip: 172.1.17.1
    mask: 255.255.255.0
    vrf: VRF_A

bgp:
  asn: 65
  router_id: 1.1.1.1

  peer_sessions:
    - name: rr-peers
      remote_as: 65
      update_source: Loopback0
      next_hop_self: true

  peer_policies:
    - name: rr-peers-ipv4
      send_community: both
    - name: rr-peers-vpnv4
      send_community: both

  ibgp_peers:
    - ip: 5.5.5.5
      description: "RR1"
      peer_session: rr-peers
      peer_policy: rr-peers-ipv4
      peer_policy_vpnv4: rr-peers-vpnv4
    - ip: 6.6.6.6
      description: "RR2"
      peer_session: rr-peers
      peer_policy: rr-peers-ipv4
      peer_policy_vpnv4: rr-peers-vpnv4

  ebgp_peers:
    - ip: 172.1.17.7
      remote_as: 65001
      description: "CE1"
      vrf: VRF_A
      route_map_in: CE1-IN
      route_map_out: CE1-OUT
